{{- range .Values.channels }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-stat-{{ . }}
  namespace: fomiller
  labels:
    compute: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-stat-logger-{{ . }}
      channel: cyr
  template:
    metadata:
      labels:
        app: chat-stat-{{ . }}
        channel: cyr
    spec:
      containers:
      - name: chat-stat
        image: 695434033664.dkr.ecr.us-east-1.amazonaws.com/fomiller-chat-stat-api:latest
        env:
          # - name: REDIS_HOST
          #   valueFrom:
          #     secretKeyRef:
          #       name: redis-endpoint
          #       key: endpoint
          - name: TWITCH_CHANNEL
            value: {{ . }}
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_secret
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_id
---
{{- end }}
