apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: twitch-credentials
  namespace: kube-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twitch-credentials
  namespace: kube-system
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: twitch-credentials
    kind: SecretStore
  target:
    name: twitch-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_secret
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_secret #AWS Secrets Manager secret key
  - secretKey: client_id
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_id #AWS Secrets Manager secret key

