apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: fomiller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::695434033664:role/external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets
  namespace: fomiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: fomiller
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: twitch-credentials
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twitch-credentials
  namespace: fomiller
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: twitch-credentials
    kind: ClusterSecretStore
  target:
    name: twitch-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_secret
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_secret #AWS Secrets Manager secret key
  - secretKey: client_id
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_id #AWS Secrets Manager secret key

