# apiVersion: v1
# kind: Service
# metadata:
#   name: chat-stat-swolenesss
#   namespace: fomiller
#   annotations:
#     alb.ingress.kubernetes.io/healthcheck-path: /
# spec:
#   type: NodePort
#   selector:
#     app: chat-stat-swolenesss
#   ports:
#     - port: 8080
#       targetPort: 8080
