{{- range .Values.channels }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-stat-logger-{{ . }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: chat-stat-logger-{{ . }}
      channel: {{ . }}
  template:
    metadata:
      labels:
        app: chat-stat-logger-{{ . }}
        channel: {{ . }}
    spec:
      containers:
      - name: chat-stat-logger
        image: 695434033664.dkr.ecr.us-east-1.amazonaws.com/fomiller-chat-stat-logger:latest
        env:
          # - name: REDIS_HOST
          #   valueFrom:
          #     secretKeyRef:
          #       name: redis-endpoint
          #       key: endpoint
          - name: REDIS_HOST
            value: redis-db-master.redis.svc.cluster.local
          - name: TWITCH_CHANNEL
            value: {{ . }}
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_secret
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_id
---
{{- end }}
