apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: twitch-credentials
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: redis-endpoint
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twitch-credentials
  namespace: {{ .Values.namespace }} 
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: twitch-credentials
    kind: ClusterSecretStore
  target:
    name: twitch-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_secret
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_secret #AWS Secrets Manager secret key
  - secretKey: client_id
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_id #AWS Secrets Manager secret key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-endpoint
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 0h
  secretStoreRef:
    name: redis-endpoint
    kind: ClusterSecretStore
  target:
    name: redis-endpoint
    creationPolicy: Owner
  data:
  - secretKey: endpoint
    remoteRef:
      key: /dev/fomiller-redis-configuration-endpoint #AWS Secrets Manager secret name

