apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-stat-cyr
  namespace: fomiller
spec:
  maxReplicas: 1
  selector:
    matchLabels:
      app: chat-stat-cyr
      channel: cyr
  template:
    metadata:
      labels:
        app: chat-stat-cyr
        channel: cyr
    spec:
      containers:
      - name: chat-stat
        image: 695434033664.dkr.ecr.us-east-1.amazonaws.com/fomiller-chat-stat-api:latest
        env:
          # - name: REDIS_HOST
          #   valueFrom:
          #     secretKeyRef:
          #       name: redis-endpoint
          #       key: endpoint
          - name: TWITCH_CHANNEL
            value: cyr
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_secret
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_id

