apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-stat-moonmoon
  namespace: fomiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-stat-moonmoon
      channel: moonmoon
  template:
    metadata:
      labels:
        app: chat-stat-moonmoon
        channel: moonmoon
    spec:
      containers:
      - name: chat-stat
        image: 695434033664.dkr.ecr.us-east-1.amazonaws.com/fomiller-chat-stat-api:latest
        env:
          # - name: REDIS_HOST
          #   value:  redis-service.chat-stat.svc.cluster.local
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-endpoint
                key: endpoint
          - name: TWITCH_CHANNEL
            value: moonmoon
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_secret
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: twitch-credentials
                key: client_id
      # - name: chat-stat-redis
      #   image: 695434033664.dkr.ecr.us-east-1.amazonaws.com/fomiller-chat-stat-api:latest
      #   env:
      #     - name: REDIS_HOST
      #       valueFrom:
      #         secretKeyRef:
      #           name: redis-endpoint
      #           key: endpoint
      #     - name: TWITCH_CHANNEL
      #       value: moonmoon
      #     - name: TWITCH_CLIENT_SECRET
      #       valueFrom:
      #         secretKeyRef:
      #           name: twitch-credentials
      #           key: client_secret
      #     - name: TWITCH_CLIENT_ID
      #       valueFrom:
      #         secretKeyRef:
      #           name: twitch-credentials
      #           key: client_id


